---
title: "Lab 6-ukn"
author: "U Kristine Nguyen"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

## Task 1

```{r}
getwd()
```

## Task 2

### (a)

```{r}
#4 section layout
lo = layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))

a = curve(dnorm(x, mean = 10, sd = 4), main = "Normal A", xlim = c(-6, 26))

b = curve(dnorm(x, mean = 10, sd = 2), main = "Normal B", xlim = c(2, 18))

c = curve(dnorm(x, mean = 5, sd = 10), main = "Normal C", xlim = c(-35, 45))

d = curve(dnorm(x, mean = 5, sd = 0.5), main = "Normal D", xlim = c(3, 7))
```

### (b)

```{r}
#4 section layout
lo = layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))

a1 = curve(dnorm(x, mean = 0, sd = 1), main = "Normal A", xlim = c(-4, 4))
axcurve = seq(2, 1000, length = 1000000)
aycurve = dnorm(axcurve, 0, 1)
polygon(c(2, axcurve, 1000), c(0, aycurve, 0), col = "Purple")
areaa = 1-pnorm(1,0,1)
areaa = round(areaa, 4)
text(0, dnorm(2, 0, 1), paste0("Area = ", areaa))

b1 = curve(dnorm(x, mean = 4, sd = 2), main = "Normal B", xlim = c(-4, 12))
bxcurve = seq(1, 4.999999, length = 1000000)
bycurve = dnorm(bxcurve, 4, 2)
polygon(c(1, bxcurve, 4.999999), c(0, bycurve, 0), col = "Light Blue")
areab = pnorm(4.999999, 4, 2) - pnorm(0.999999, 4, 2)
areab = round(areab, 4)
text(7, dnorm(1, 4, 2), paste0("Area = ", areab))

c1 = curve(dnorm(x, mean = 10, sd = 4), main = "Normal C", xlim = c(-6, 26))
cxcurve = seq(-1000, 9.999999, length = 1000000)
cycurve = dnorm(cxcurve, 10, 4)
polygon(c(-1000, cxcurve, 9.999999), c(0, cycurve, 0), col = "Light Pink")
areac = pnorm(9.999999, 10, 4)
areac = round(areac, 4)
text(13, dnorm(2, 10, 4), paste0("Area = ", areac))

d1 = curve(dnorm(x, mean = -2, sd = 0.5), main = "Normal D", xlim = c(-4, 0))
dxcurve = seq(-2.999999, -2, length = 1000000)
dycurve = dnorm(dxcurve, -2, 0.5)
polygon(c(-2.999999, dxcurve, -2), c(0, dycurve, 0), col = "Cyan")
aread = pnorm(-2, -2, 0.5) - pnorm(3, -2, 0.5)
aread = round(aread, 4)
text(-1, dnorm(-1, -2, 0.5), paste0("Area = ", aread))
```

## Task 3

### (a) 3 Gamma Plots

```{r}
ga = curve(dgamma(x, shape = 1, scale = 1), main = "Gamma A", xlim = c(-0.1,3.5))

gb = curve(dgamma(x, shape = 3, scale = 1), main = "Gamma B", xlim = c(-0.3,10))

gc = curve(dgamma(x, shape = 5, scale = 1), main = "Gamma C", xlim = c(0,15))
```

### (b) 3 Gamma Plots with Probability and Area

```{r}
ga1 = curve(dgamma(x, shape = 3, scale = 2), main = "Gamma A", xlim = c(-0.2,20))
gax = seq(2.000001, 4.999999, length = 1000000)
gay = dgamma(gax, shape = 3, scale = 2)
polygon(c(2.000001, gax, 4.999999), c(0, gay, 0), col = "Light Blue")
areaga = pgamma(4.999999, shape = 3, scale = 2) - pgamma(2, shape = 3, scale = 2)
areaga = round(areaga, 4)
text(5, dgamma(1, shape = 3, scale = 2), paste0("Area = ", areaga))

gb1 = curve(dgamma(x, shape = 6, scale = 3), main = "Gamma B", xlim = c(0.2, 6))
gbx = seq(1, 4, length = 1000000)
gby = dgamma(gbx, shape = 6, scale = 3)
polygon(c(1, gbx, 4), c(0, gby, 0), col = "Light Pink")
areagb = pgamma(4, shape = 6, scale = 3) - pgamma(2.999999, shape = 6, scale = 3)
areagb = round(areagb, 4)
text(5, dgamma(1, shape = 6, scale = 3), paste0("Area = ", areagb))

gc1 = curve(dgamma(x, shape = 2, scale = 4), main = "Gamma C", xlim = c(-0.3,20))
gcx = seq(3, 5.999999, length = 1000000)
gcy = dgamma(gcx, shape = 2, scale = 4)
polygon(c(3, gcx, 5.999999), c(0, gcy, 0), col = "Cyan")
areagc = pgamma(5.999999, shape = 2, scale = 4) - pgamma(2.999999, shape = 2, scale = 4)
areagc = round(areagc, 4)
text(10, dgamma(0, shape = 2, scale = 4), paste0("Area = ", areagc))
```

## Task 4

### (a) 4 Chi-Square Plots

```{r}
#4 section layout
lo = layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))

chia = curve(dgamma(x, shape = 0.5, scale = 2), main = "Chi Square A: df = 1", xlim = c(-1,3))

chib = curve(dgamma(x, shape = 1, scale = 2), main = "Chi Square B: df = 2", xlim = c(-1.5, 8))

chic = curve(dgamma(x, shape = 2, scale = 2), main = "Chi Square C: df = 4", xlim = c(-0.3,15))

chid = curve (dgamma(x, shape = 10, scale = 2), main = "Chi Square D: df = 20", xlim = c(3, 40))
```

### (b) 3 Chi-Square with Probability and Area

```{r}
chi1 = curve(dgamma(x, shape = 1, scale = 2), main = "Chi Square A: df = 2", xlim = c(-1.5,8))
chix1 = seq(2, 4, length = 1000000)
chiy1 = dgamma(chix1, shape = 1, scale = 2)
polygon(c(2, chix1, 4), c(0, chiy1, 0), col = "Light Blue")
areac1 = pgamma(4, shape = 1, scale = 2) - pgamma(1.999999, shape = 1, scale = 2)
areac1 = round(areac1, 4)
text(5, dgamma(1, shape = 1, scale = 2), paste0("Area = ", areac1))

chi2 = curve(dgamma(x, shape = 1.5, scale = 2), main = "Chi Square B: df = 3", xlim = c(-2, 10))
chix2 = seq(3, 5, length = 1000000)
chiy2 = dgamma(chix2, shape = 1.5, scale = 2)
polygon(c(3, chix2, 5), c(0, chiy2, 0), col = "Light Pink")
areac2 = pgamma(5, shape = 1.5, scale = 2) - pgamma(2.999999, shape = 1.5, scale = 2)
areac2 = round(areac2, 4)
text(6, dgamma(1, shape = 1.5, scale = 2), paste0("Area = ", areac2))

chi3 = curve(dgamma(x, shape = 10, scale = 2), main = "Chi Square C: df = 20", xlim = c(3,40))
chix3 = seq(10.000001, 21, length = 1000000)
chiy3 = dgamma(chix3, shape = 10, scale = 2)
polygon(c(10.000001, chix3, 21), c(0, chiy3, 0), col = "Purple")
areac3 = pgamma(21, shape = 10, scale = 2) - pgamma(10, shape = 10, scale = 2)
areac3 = round(areac3, 4)
text(27, dgamma(1, shape = 10, scale = 2), paste0("Area = ", areac3))
```

## Task 5

### (a) 4 Weibull Plots

```{r}
#4 section layout
lo = layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))

dwa = curve(dweibull(x, shape = 1, scale = 1), main = "Weibull Plot A", xlim = c(-0.5,3))

dwb = curve(dweibull(x, shape = 2, scale = 1), main = "Weibull Plot B", xlim = c(-0.3, 3))

dwc = curve(dweibull(x, shape = 4, scale = 2), main = "Weibull Plot C", xlim = c(-0.5, 4))

dwd = curve(dweibull(x, shape = 2, scale = 2), main = "Weibull Plot D", xlim = c(-1, 7))
```

### (b) 3 Weibull with Probability and Area

```{r}
dwb = curve(dweibull(x, shape = 2, scale = 1), main = "Weibull Plot A", xlim = c(-0.3, 3))
dwbx = seq(-1000, 1, length = 1000000)
dwby = dweibull(dwbx, shape = 2, scale = 1)
polygon(c(-1000, dwbx, 1), c(0, dwby, 0), col = "Light Pink")
areawb = pweibull(1, shape = 2, scale = 1)
areawb = round(areawb, 4)
text(2, dweibull(1, shape = 2, scale = 1), paste0("Area = ", areawb))

dwc = curve(dweibull(x, shape = 4, scale = 2), main = "Weibull Plot B", xlim = c(-0.5, 4))
dwcx = seq(-1000, 1.5, length = 1000000)
dwcy = dweibull(dwcx, shape = 4, scale = 2)
polygon(c(-1000, dwcx, 1.5), c(0, dwcy, 0), col = "Purple")
areawc = pweibull(1.5, shape = 4, scale = 2)
areawc = round(areawc, 4)
text(3, dweibull(1, shape = 4, scale = 2), paste0("Area = ", areawc))

dwd = curve(dweibull(x, shape = 2, scale = 2), main = "Weibull Plot C", xlim = c(-1, 7))
dwdx = seq(3, 1000, length = 1000000)
dwdy = dweibull(dwdx, shape = 2, scale = 2)
polygon(c(3, dwdx, 1000), c(0, dwdy, 0), col = "Light Blue")
areawd = 1 - pweibull(3, shape = 2, scale = 2)
areawd = round(areawd, 4)
text(5, dweibull(1, shape = 2, scale = 2), paste0("Area = ", areawd))
```

## Task 6

### (a) 4 Plots

```{r}
#4 section layout
lo = layout(matrix(1:4, nr = 2, nc = 2, byrow = TRUE))

b1 = curve(dbeta(x, shape1 = 2, shape2 = 3), main = "Beta Distribution A", xlim = c(-0.2, 1.2))

b2 = curve(dbeta(x, shape1 = 8, shape2 = 4), main = "Beta Distribution B", xlim = c(-0.2, 1.2))

b3 = curve(dbeta(x, shape1 = 10, shape2 = 2), main = "Beta Distribution C", xlim = c(-0.2, 1.2))

b4 = curve(dbeta(x, shape1 = 6, shape2 = 7), main = "Beta Distribution D", xlim = c(-0.2, 1.2))
```

### (b) Probability and Area

```{r}
b1 = curve(dbeta(x, shape1 = 2, shape2 = 3), main = "Beta Distribution A", xlim = c(-0.2, 1.2))
b1x = seq(0.4, 1000, length = 1000000)
b1y = dbeta(b1x, shape1 = 2, shape2 = 3)
polygon(c(0.4, b1x, 1000), c(0, b1y, 0), col = "Light Blue")
areab1 = 1 - pbeta(0.4, shape1 = 2, shape2 = 3)
areab1 = round(areab1, 4)
text(0.2, dbeta(3, shape1 = 2, shape2 = 3), paste0("Area = ", areab1))

b2 = curve(dbeta(x, shape1 = 8, shape2 = 4), main = "Beta Distribution B", xlim = c(-0.2, 1.2))
b2x = seq(-1000, 0.6, length = 1000000)
b2y = dbeta(b2x, shape1 = 8, shape2 = 4)
polygon(c(-1000, b2x, 0.6), c(0, b2y, 0), col = "Purple")
areab2 = pbeta(0.6, shape1 = 8, shape2 = 4)
areab2 = round(areab2, 4)
text(0.75, dbeta(2, shape1 = 8, shape2 = 4), paste0("Area = ", areab2))

b4 = curve(dbeta(x, shape1 = 6, shape2 = 7), main = "Beta Distribution C", xlim = c(-0.2, 1.2))
b4x = seq(0.5, 1000, length = 1000000)
b4y = dbeta(b4x, shape1 = 6, shape2 = 7)
polygon(c(0.5, b4x, 1000), c(0, b4y, 0), col = "Light Pink")
areab4 = 1 - pbeta(0.5, shape1 = 6, shape2 = 7)
areab4 = round(areab4, 4)
text(0.3, dbeta(2, shape1 = 6, shape2 = 7), paste0("Area = ", areab4))
```

## Task 7

```{r}
library(package1)
myncurve(6, 10, 5)
```

